name: whatbit
version: 0.0.1
description: Web app to convert a hex string to (byte,bit) number pairs
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
  hexbit:
    path: ../dart-bertlv
dev_dependencies:
#  unittest: any
transformers:
- angular:
    html_files:
      - lib/component/unhex.html
      - lib/component/unhex.css
    dart_sdk: "/usr/local/opt/dart/libexec"
